# Generated by Django 5.2.4 on 2025-11-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our Traditional Ice Creams Since 1950', max_length=200)),
                ('description', models.TextField()),
                ('founder_name', models.CharField(default='Founder Unknown', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
