# Generated by Django 5.2.4 on 2025-11-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icecreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icecream_flavours', models.CharField(max_length=250)),
                ('icecream_price', models.CharField(max_length=250)),
                ('icecream_img', models.FileField(default=None, max_length=250, null=True, upload_to='icecream')),
            ],
        ),
    ]
