# Generated by Django 5.2.5 on 2025-12-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidata',
            old_name='class_name',
            new_name='classname',
        ),
        migrations.RenameField(
            model_name='apidata',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
